const lessonTitle = "面具";

const lessonData = [
    // 正文第 1 段
    ["海森", "hǎi sēn", "Haisen (Name)", "Haisen"],
    ["是一个", "shì yí gè", "was a", "adalah seorang"],
    ["二流演员", "èr liú yǎn yuán", "second-rate actor", "pelakon kelas kedua"],
    ["，", "", "", ""],
    ["他的", "tā de", "his", "dia punya"],
    ["经纪人", "jīng jì rén", "agent / manager", "ejen / pengurus"],
    ["给他", "gěi tā", "for him", "kepada dia"],
    ["介绍le", "jiè shào le", "introduced", "memperkenalkan"],
    ["一份", "yí fèn", "a (measure word for jobs)", "sebuah"],
    ["工作", "gōng zuò", "job / work", "pekerjaan"],
    ["，", "", "", ""],
    ["大富翁", "dà fù wēng", "tycoon / millionaire", "orang kaya besar / jutawan"],
    ["费德诺", "fèi dé nuò", "Fednor (Name)", "Fednor"],
    ["聘请", "pìn qǐng", "hired / employed", "menggaji / mengupah"],
    ["他", "tā", "him", "dia"],
    ["去给", "qù gěi", "to go and for", "pergi untuk"],
    ["父亲", "fù qīn", "father", "bapa"],
    ["老费德诺", "lǎo fèi dé nuò", "Old Fednor", "Old Fednor"],
    ["演场戏", "yǎn cháng xì", "put on a play / act out a scene", "berlakon satu babak / bersandiwara"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 2 段
    ["老费德诺", "lǎo fèi dé nuò", "Old Fednor", "Old Fednor"],
    ["病重", "bìng zhòng", "seriously ill", "sakit tenat / parah"],
    ["住院了", "zhù yuàn le", "hospitalized", "dimasukkan ke hospital"],
    ["，", "", "", ""],
    ["费德诺先生", "fèi dé nuò xiān sheng", "Mr. Fednor", "Encik Fednor"],
    ["本该在", "běn gāi zài", "should have been at", "sepatutnya berada di"],
    ["医院里", "yī yuàn lǐ", "inside the hospital", "dalam hospital"],
    ["陪着他", "péi zhe tā", "accompanying him", "menemani beliau"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "namun / tetapi"],
    ["费德诺先生", "fèi dé nuò xiān sheng", "Mr. Fednor", "Encik Fednor"],
    ["很忙", "hěn máng", "very busy", "sangat sibuk"],
    ["，", "", "", ""],
    ["根本", "gēn běn", "at all / simply", "langsung"],
    ["挤不出", "jǐ bù chū", "cannot squeeze out (time)", "tidak dapat meluangkan / memeras keluar"],
    ["那么多的", "nà me duō de", "that much's", "sebegitu banyak punya"],
    ["时间", "shí jiān", "time", "masa"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 3 段
    ["但他", "dàn tā", "But he", "Namun dia"],
    ["又担心", "yòu dān xīn", "also worried", "pula bimbang"],
    ["被人", "bèi rén", "by people", "oleh orang ramai"],
    ["说长论短", "shuō cháng lùn duǎn", "gossip / criticize / point fingers", "mengata-ngata / mengumpat / digosipkan"],
    ["，", "", "", ""],
    ["这时", "zhè shí", "at this moment", "pada waktu ini"],
    ["他就", "tā jiù", "he then", "dia terus"],
    ["想到了", "xiǎng dào le", "thought of", "teringat akan"],
    ["和自己", "hé zì jǐ", "with himself", "dengan diri sendiri"],
    ["长得很像的", "zhǎng de hěn xiàng de", "looks very similar's", "mempunyai rupa sangat mirip punya"],
    ["海森", "hǎi sēn", "Haisen", "Haisen"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 4 段
    ["经过", "jīng guò", "After", "Selepas melalui"],
    ["两天的", "liǎng tiān de", "two days'", "dua hari punya"],
    ["练习", "liàn xí", "practice", "latihan"],
    ["，", "", "", ""],
    ["海森", "hǎi sēn", "Haisen", "Haisen"],
    ["已学得", "yǐ xué de", "had learned until", "sudah meniru sehingga"],
    ["惟妙惟肖", "wéi miào wéi xiào", "remarkably lifelike / vivid", "tersangat mirip / seiras benar / hidup"],
    ["，", "", "", ""],
    ["固定", "", "", ""],
    ["就连", "jiù lián", "even", "bahkan"],
    ["费德诺先生", "fèi dé nuò xiān sheng", "Mr. Fednor", "Encik Fednor"],
    ["本人", "běn rén", "himself", "sendiri"],
    ["也", "yě", "also", "pun"],
    ["分辨不出来", "fēn biàn bù chū lái", "cannot distinguish", "tidak dapat membedakan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段
    ["再戴上", "zài dài shàng", "Then put on", "Ditambah pula memakai"],
    ["根据", "gēn jù", "according to", "berdasarkan"],
    ["费德诺先生", "fèi dé nuò xiān sheng", "Mr. Fednor's", "Encik Fednor punya"],
    ["面貌", "miàn mào", "facial features / looks", "rupa paras"],
    ["特制的", "tè zhì de", "specially made", "dibuat khas punya"],
    ["橡皮面具", "xiàng pí miàn jù", "rubber mask", "topeng getah"],
    ["，", "", "", ""],
    ["简直就是", "jiǎn zhí jiù shì", "simply is / literally", "boleh dikatakan sebagai"],
    ["费德诺先生", "fèi dé nuò xiān sheng", "Mr. Fednor", "Encik Fednor"],
    ["再生了", "zài shēng le", "reborn / reincarnated", "hidup semula"],
    ["。", "", "", ""],
    ["他就", "tā jiù", "He then", "Dia pun"],
    ["和费德诺先生", "hé fèi dé nuò xiān sheng", "with Mr. Fednor", "dengan Encik Fednor"],
    ["签下了", "qiān xià le", "signed down", "menandatangani"],
    ["合同", "hé tong", "contract", "kontrak / perjanjian"],
    ["，", "", "", ""],
    ["正式演出", "zhèng shì yǎn chū", "officially perform", "bermula lakonan rasmi"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 6 段
    ["第一次", "dì yī cì", "The first time", "Kali pertama"],
    ["走进", "zǒu jìn", "walking into", "melangkah masuk ke"],
    ["病房", "bìng fáng", "ward / sickroom", "bilik wad pesakit"],
    ["时", "shí", "when", "apabila / ketika"],
    ["，", "", "", ""],
    ["海森", "hǎi sēn", "Haisen", "Haisen"],
    ["还有些", "hái yǒu xiē", "still had some", "masih ada sedikit perasaan"],
    ["忐忑", "tǎn tè", "perturbed / nervous / textually uneasy", "berdebar-debar / gelisah / bimbang"],
    ["，", "", "", ""],
    ["他老老实实地", "tā lǎo lǎo shí shí de", "honestly / obediently", "dengan sangat jujur dan patuh"],
    ["坐到床边", "zuò dào chuáng biān", "sat by the bedside", "duduk di tepi katil"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 7 段
    ["老费德诺先生", "lǎo fèi dé nuò xiān sheng", "Old Mr. Fednor", "Encik Fednor tua"],
    ["看到他", "kàn dào tā", "seeing him", "melihat ketibaannya"],
    ["到来", "dào lái", "arrival", "datang"],
    ["很高兴", "hěn gāo xìng", "very happy", "berasa sangat gembira"],
    ["，", "", "", ""],
    ["絮絮叨叨地", "xù xù dāo dāo de", "chattering / repeating repetitively", "membebel-bebel / bercakap panjang lebar"],
    ["说起了", "shuō qǐ le", "talked about / began speaking of", "mula menceritakan tentang"],
    ["他童年的", "tā tóng nián de", "his childhood's", "masa kanak-kanak dia punya"],
    ["趣事", "qù shì", "interesting anecdotes / fun stories", "cerita-cerita lucu"],
    ["。", "", "", ""],
    ["海森", "hǎi sēn", "Haisen", "Haisen"],
    ["不敢搭腔", "bù gǎn dā qiāng", "dare not answer / join the conversation", "tidak berani menyampuk / menjawab"],
    ["，", "", "", ""],
    ["只是", "zhǐ shì", "just / merely", "hanya"],
    ["在一边", "zài yì biān", "on the side", "di sebelah tepi"],
    ["不时地", "bù shí de", "from time to time", "dari semasa ke semasa"],
    ["应和一句", "yìng hè yí jù", "echoed a sentence / responded", "mengia-iyakan sepatah"],
    ["，", "", "", ""],
    ["或是", "huò shì", "or", "ataupun"],
    ["笑笑", "xiào xiao", "smile a bit", "tersenyum sedikit"],
    ["。", "", "", ""],
    ["但老费德诺先生", "dàn lǎo fèi dé nuò xiān sheng", "But Old Mr. Fednor", "Namun Encik Fednor tua"],
    ["似乎", "sì hū", "seemingly / appeared", "nampaknya seolah-olah"],
    ["已经", "yǐ jīng", "already", "sudah pun"],
    ["很满足了", "hěn mǎn zú le", "very satisfied", "berpuas hati sangat"],
    ["，", "", "", ""],
    ["脸上", "liǎn shàng", "on the face", "pada muka beliau"],
    ["一直", "yī zhí", "all along", "sentiasa"],
    ["带着微笑", "dài zhe wēi xiào", "bearing a smile", "mengukir senyuman"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 8 段
    ["海森", "hǎi sēn", "Haisen", "Haisen"],
    ["看", "kàn", "saw that", "melihat"],
    ["规定", "guī dìng", "stipulated / required", "yang ditetapkan punya"],
    ["陪护的", "péi hù de", "accompanying / nursing's", "menemani pesakit punya"],
    ["时间", "shí jiān", "time", "masa"],
    ["到了", "dào le", "arrived", "dah sampai"],
    ["，", "", "", ""],
    ["就", "jiù", "then", "latu terus"],
    ["站起身来", "zhàn qǐ shēn lái", "stood up body", "bangun berdiri"],
    ["。", "", "", ""],
    ["老费德诺", "lǎo fèi dé nuò", "Old Fednor", "Old Fednor"],
    ["一把", "yì bǎ", "one grab (measure word for action)", "dengan segera"],
    ["拉住了", "lā zhù le", "grabbed / held tight", "memegang erat / menarik"],
    ["他的", "tā de", "his", "dia punya"],
    ["胳膊", "gē bo", "arm", "lengan"],
    ["，", "", "", ""],
    ["乞怜地", "qǐ lián de", "imploringly / piteously", "dengan penuh memohon belas kasihan / rayuan pilu"],
    ["望着他", "wàng zhe tā", "gazing at him", "memandang ke arah dia"],
    ["，", "", "", ""],
    ["“", "", "", ""],
    ["再陪我", "zài péi wǒ", "accompany me more", "Temanlah bapa lagi"],
    ["一会儿吧", "yí huì r ba", "a little while", "sekejap lah"],
    ["，", "", "", ""],
    ["我知道", "wǒ zhī dào", "I know", "bapa tahu"],
    ["你很忙", "nǐ hěn máng", "you are very busy", "kamu sangat sibuk"],
    ["，", "", "", ""],
    ["但我", "dàn wǒ", "but I", "namun bapa"],
    ["真的", "zhēn de", "really", "sungguh-sungguh"],
    ["想跟你", "xiǎng gēn nǐ", "want to with you", "mahu dengan kamu"],
    ["再说说话呀", "zài shuō shuō huà ya", "talk some more words", "berbual-bual lagi ya"],
    ["。", "", "", ""],
    ["好吗", "hǎo ma", "OK", "boleh kan"],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 9 段
    ["海森", "hǎi sēn", "Haisen", "Haisen"],
    ["看到", "kàn dào", "seeing", "melihat"],
    ["老人", "lǎo rén", "old man's", "orang tua punya"],
    ["眼睛里", "yǎn jing lǐ", "inside the eyes", "dalam mata"],
    ["那份", "nà fèn", "that sum of", "perasaan yang itu"],
    ["热切的", "rè qiè de", "earnest / fervent", "mendalam / bersungguh-sungguh"],
    ["期待", "qī dài", "anticipation / expectation", "harapan"],
    ["和", "hé", "and", "dan"],
    ["隐隐的", "yǐn yǐn de", "faint / hidden", "sedikit pudar / tersirat"],
    ["凄楚", "qī chǔ", "misery / sadness / grief", "kesedihan pilu / kesayuan"],
    ["，", "", "", ""],
    ["不忍", "bù rěn", "cannot bear to", "tidak sampai hati untuk"],
    ["拒绝", "jù jué", "refuse", "menolak"],
    ["，", "", "", ""],
    ["就又", "jiù yòu", "then again", "lalu sekali lagi"],
    ["坐到", "zuò dào", "sat down to", "duduk di"],
    ["床前", "chuáng qián", "bedside", "depan katil"],
    ["。", "", "", ""],
    ["老费德诺先生", "lǎo fèi dé nuò xiān sheng", "Old Mr. Fednor", "Encik Fednor tua"],
    ["又说了", "yòu shuō le", "spoke for another", "berkata lagi"],
    ["10分钟", "shí fēn zhōng", "10 minutes", "sepuluh minit"],
    ["，", "", "", ""],
    ["这才", "zhè cái", "only then", "barulah barangkali"],
    ["和他", "hé tā", "with him", "dengan dia"],
    ["依依不舍地", "yī yī bù shě de", "reluctantly to part", "dengan rasa keberatan untuk berpisah"],
    ["告别", "gào bié", "bid farewell", "mengucapkan selamat tinggal"],
    ["，", "", "", ""],
    ["并", "bìng", "and also", "serta"],
    ["热切地", "rè qiè de", "earnestly", "dengan penuh harapan"],
    ["要求他", "yāo qiú tā", "requested him", "meminta dia"],
    ["明天", "míng tiān", "tomorrow", "esok hari"],
    ["准时", "zhǔn shí", "on time / punctually", "tepat pada masanya"],
    ["赶过来", "gǎn guò lái", "rush over", "datang ke sini"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 10 段
    ["一出", "yī chū", "As soon as stepping out of", "Sebaik sahaja melangkah keluar dari"],
    ["医院", "yī yuàn", "hospital", "hospital"],
    ["，", "", "", ""],
    ["经纪人", "jīng jì rén", "agent", "pengurus itu"],
    ["就递给", "jiù dì gěi", "straightaway handed to", "terus menyerahkan kepada"],
    ["他", "tā", "him", "dia"],
    ["一张", "yì zhāng", "a (measure word for check)", "sekeping"],
    ["支票", "zhī piào", "check", "cek wang"],
    ["，", "", "", ""],
    ["海森", "hǎi sēn", "Haisen", "Haisen"],
    ["高兴地", "gāo xìng de", "happily", "dengan gembira"],
    ["收起了", "shōu qǐ le", "put away / pocketed", "menyimpan"],
    ["支票", "zhī piào", "check", "cek wang itu"],
    ["。", "", "", ""],
    ["这时", "zhè shí", "At this moment", "Pada waktu ini"],
    ["，", "", "", ""],
    ["一个", "yí gè", "a", "seorang"],
    ["年轻人", "nián qīng rén", "young man", "pemuda"],
    ["走过来", "zǒu guò lái", "walked over", "melangkah datang ke mari"],
    ["，", "", "", ""],
    ["声称", "shēng chēng", "claimed / professed", "mendakwa diri"],
    ["是", "shì", "was", "adalah"],
    ["《", "", "", ""],
    ["太阳快报", "tài yáng kuài bào", "The Sun Express (Newspaper)", "Sun Express"],
    ["》", "", "", ""],
    ["的", "de", "out", ""],
    ["记者", "jì zhě", "reporter / journalist", "wartawan"],
    ["，", "", "", ""],
    ["听闻", "tīng wén", "heard news that", "terdengar khabar bahawa"],
    ["费德诺先生", "fèi dé nuò xiān sheng", "Mr. Fednor", "Encik Fednor"],
    ["放下", "fàng xià", "putting down", "meletakkan tepi"],
    ["繁忙的", "fán máng de", "busy / hectic", "yang tersangat sibuk punya"],
    ["工作", "gōng zuò", "work", "urusan kerja"],
    ["，", "", "", ""],
    ["每天", "měi tīan", "every day", "setiap hari"],
    ["都赶到", "dōu gǎn dào", "all rushed to", "pasti bergegas ke"],
    ["医院", "yī yuàn", "hospital", "hospital"],
    ["来陪伴", "lái péi bàn", "come to accompany", "datang menemani"],
    ["父亲", "fù qīn", "father", "bapa"],
    ["，", "", "", ""],
    ["很是", "hěn shì", "was very", "amat / sangat"],
    ["感动", "gǎn dòng", "moved / touched", "terharu"],
    ["，", "", "", ""],
    ["特地", "tè dì", "specially / purposefully", "sengaja / khas"],
    ["来采访的", "lái cǎi fǎng de", "come to interview", "datang untuk menemu ramah punya"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 11 段
    ["海森", "hǎi sēn", "Haisen", "Haisen"],
    ["不愧是一个", "bú kuì shì yí gè", "truly worthy of being a", "memang layak digelar seorang"],
    ["演员", "yǎn yuán", "actor", "pelakon"],
    ["，", "", "", ""],
    ["很快", "hěn kuài", "very quickly", "dengan sangat cepat"],
    ["就酝酿出了", "jiù yùn niàng chū le", "brewed up / conjured up", "berjaya membangkitkan keluar"],
    ["情绪", "qíng xù", "emotion / mood", "perasaan / emosi"],
    ["，", "", "", ""],
    ["来了一个", "lái le yí gè", "performed a", "membuat satu"],
    ["现场表演", "xiàn cháng bǎn yǎn", "on-the-spot performance / live show", "persembahan spontan di lokasi"],
    ["。", "", "", ""],
    ["他诉说了", "tā sù shuō le", "He expressed / recounted", "Dia menceritakan tentang"],
    ["自己", "zì jǐ", "oneself's", "diri sendiri punya"],
    ["对父亲的", "duì fù qīn de", "towards father's", "terhadap bapa punya"],
    ["爱", "ài", "love", "kasih sayang"],
    ["，", "", "", ""],
    ["诉说了", "sù shuō le", "recounted", "menceritakan tentang"],
    ["父亲", "fù qīn", "father", "bapa"],
    ["对自己的", "duì zì jǐ de", "towards himself's", "terhadap diri sendiri punya"],
    ["好", "hǎo", "kindness / good", "kebaikan"],
    ["，", "", "", ""],
    ["说到", "shuō dào", "talking to", "apabila bercakap sampai ke"],
    ["动情处", "dòng qíng chù", "touching part / emotional point", "bahagian yang menyayat hati"],
    ["，", "", "", ""],
    ["还流下了", "hái liú xià le", "even shed down", "malah turut mengalirkan"],
    ["几滴", "jǐ dī", "a few drops of", "beberapa titis"],
    ["眼泪", "yǎn lèi", "tears", "air mata"],
    ["，", "", "", ""],
    ["感动得", "gǎn dòng de", "moved until", "menyebabkan terharu sehingga"],
    ["记者", "jì zhě", "reporter's", "wartawan itu punya"],
    ["眼圈儿", "yǎn quānr", "rim of eyes", "lingkaran mata"],
    ["都红了", "dōu hóng le", "all turned red", "menjadi merah"],
    ["，", "", "", ""],
    ["不失时机地", "bù shī shí jī de", "losing no time / seizing the opportunity", "tanpa melepaskan peluang emas"],
    ["给他", "gěi tā", "for him", "kepada dia"],
    ["拍了一张", "pāi le yì zhāng", "snapped a (photo)", "mengambil sekeping gambar"],
    ["大特写", "dà tè xiě", "close-up shot", "foto fokus dekat (close-up)"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 12 段
    ["第二天", "dì èr tīan", "The next day", "Keesokan harinya"],
    ["一早", "yī zǎo", "early morning", "awal-awal pagi lagi"],
    ["，", "", "", ""],
    ["费德诺先生", "fèi dé nuò xiān sheng", "Mr. Fednor", "Encik Fednor"],
    ["就打来了", "jiù dǎ lái le", "straightaway called over", "terus menelefon datang"],
    ["电话", "diàn huà", "telephone", "telefon"],
    ["，", "", "", ""],
    ["说", "shuō", "saying", "dan berkata bahawa"],
    ["《", "", "", ""],
    ["太阳快报", "tài yáng kuài bào", "The Sun Express", "Sun Express"],
    ["》", "", "", ""],
    ["登出了", "dēng chū le", "published / printed", "telah menyiarkan keluar"],
    ["那篇", "nà piān", "that", "rencana yang itu"],
    ["专访", "zhuān fǎng", "exclusive interview", "wawancara khas"],
    ["，", "", "", ""],
    ["非常精彩", "fēi cháng jīng cǎi", "very wonderful / brilliant", "tersangat hebat / menarik"],
    ["，", "", "", ""],
    ["有很多人", "yǒu hěn duō rén", "there were many people", "ada ramai orang"],
    ["打电话", "dǎ diàn huà", "making phone calls", "menelefon"],
    ["对他", "duì tā", "towards him", "kepada dia"],
    ["表示", "biǎo shì", "expressing", "menyatakan"],
    ["敬意", "jìng yì", "respect / salute", "rasa hormat / sanjungan"],
    ["，", "", "", ""],
    ["还有", "hái yǒu", "there were also", "malah ada juga"],
    ["几个", "jǐ gè", "a few", "beberapa buah"],
    ["合作伙伴", "hé zuò huǒ bàn", "cooperative partners / business partners", "rakan kongsi perniagaan"],
    ["要尽快", "yào jìn kuài", "want to as soon as possible", "mahu secepat mungkin"],
    ["跟他", "gēn tā", "with him", "dengan dia"],
    ["签订", "qiān dìng", "sign (a contract)", "menandatangani"],
    ["供货合同", "gōng huò hé tong", "supply contract", "kontrak pembekalan barangan"],
    ["。", "", "", ""],
    ["他要", "tā yào", "He wanted to", "Dia berniat mahu"],
    ["提高", "tí gāo", "raise / increase", "menaikkan"],
    ["付给", "fù gěi", "paid to", "yang dibayar kepada"],
    ["海森的", "hǎi sēn de", "Haisen's", "Haisen punya"],
    ["酬金", "chóu jīn", "remuneration / payment", "wang ganjaran / upah bayaran"],
    ["，", "", "", ""],
    ["还要把", "hái yào bǎ", "also want to object particle", "malah mahu menyebabkan"],
    ["合同期限", "hé tong qī xiàn", "contract period / duration", "tempoh kontrak"],
    ["延长", "yán cháng", "extend / prolong", "dilanjutkan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 13 段
    ["之后", "zhī hòu", "Afterwards / from then on", "Selepas daripada itu"],
    ["，", "", "", ""],
    ["海森", "hǎi sēn", "Haisen", "Haisen"],
    ["继续", "jì xù", "continued", "berterusan"],
    ["如约", "rú yuē", "as agreed / as scheduled", "seperti yang dijanjikan"],
    ["赶到", "gǎn dào", "rushed to", "bergegas ke"],
    ["医院", "yī yuàn", "hospital", "hospital"],
    ["，", "", "", ""],
    ["慢慢地", "màn màn de", "gradually / slowly", "perlahan-lahan / lama-kelamaan"],
    ["他不仅", "tā bù jǐn", "he not only", "dia bukan sahaja"],
    ["听", "tīng", "listened to", "mendengar"],
    ["老费德诺先生", "lǎo fèi dé nuò xiān sheng", "Old Mr. Fednor", "Encik Fednor tua"],
    ["说话", "shuō huà", "speak words", "bercakap"],
    ["，", "", "", ""],
    ["还给他", "hái gěi tā", "also for him", "malah turut kepada dia"],
    ["讲些", "jiǎng xiē", "tell some", "menceritakan sedikit"],
    ["笑话", "xiào hua", "jokes", "cerita jenaka"],
    ["。", "", "", ""],
    ["老费德诺", "lǎo fèi dé nuò", "Old Fednor", "Old Fednor"],
    ["经常来", "jīng cháng lái", "frequently", "sering kali"],
    ["笑得", "xiào de", "laughed until", "tertawa sehingga"],
    ["前仰后合", "qián yǎng hòu hé", "rock with laughter / doubled up", "terkekek-kekek terpingkal-pingkal"],
    ["，", "", "", ""],
    ["像个孩子", "xiàng gè hái zi", "like a child", "bagaikan seorang budak kecil"],
    ["一样", "yí yàng", "the same", "sedemikian"],
    ["兴奋", "xīng fèn", "excited", "teruja / seronok"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 14 段
    ["这天", "zhè tiān", "This day", "Pada hari ini"],
    ["下午", "xià wǔ", "afternoon", "petang"],
    ["，", "", "", ""],
    ["海森", "hǎi sēn", "Haisen", "Haisen"],
    ["像往常一样", "xiàng wǎng cháng yí yàng", "as usual", "seperti hari-hari biasa"],
    ["赶到", "gǎn dào", "rushed to", "bergegas ke"],
    ["医院", "yī yuàn", "hospital", "hospital"],
    ["。", "", "", ""],
    ["老费德诺", "lǎo fèi dé nuò", "Old Fednor's", "Old Fednor punya"],
    ["脸色", "liǎn sè", "complexion / face color", "air muka / rupa wajah"],
    ["很不好", "hěn bù hǎo", "very bad", "sangat tidak baik"],
    ["，", "", "", ""],
    ["主治医生", "zhǔ zhì yī shēng", "attending physician / chief doctor", "doktor pakar utama"],
    ["告诉", "gào su", "told", "memberitahu kepada"],
    ["海森", "hǎi sēn", "Haisen", "Haisen"],
    ["，", "", "", ""],
    ["老费德诺的", "lǎo fèi dé nuò de", "Old Fednor's", "Old Fednor punya"],
    ["血液", "xuè yè", "blood", "darah"],
    ["化验中", "huà yàn zhōng", "in the laboratory assay", "dalam ujian makmal"],
    ["发现了", "fā xiàn le", "discovered", "telah menemui"],
    ["一种", "yì zhǒng", "a kind of", "sejenis"],
    ["病毒变异", "bìng dú biàn yì", "virus mutation", "mutasi virus / variasi virus"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 15 段
    ["这种", "zhè zhǒng", "This kind of", "Virus jenis ini"],
    ["病毒", "bìng dú", "virus", "virus"],
    ["到现在为止", "dào xiàn zài wéi zhǐ", "up until now", "sehingga ke hari ini"],
    ["还没有", "hái méi yǒu", "still do not have", "masih belum mempunyai"],
    ["药物", "yào wù", "medicine / drugs", "ubat-ubatan"],
    ["可以", "kě yǐ", "can", "yang boleh"],
    ["抑制它", "yì zhì tā", "suppress it / inhibit it", "menyekatnya / membendungnya"],
    ["，", "", "", ""],
    ["随时会", "suí shí huì", "at any time would", "pada bila-bila masa sahaja akan"],
    ["要了", "yào le", "take (away)", "meragut"],
    ["老费德诺的", "lǎo fèi dé nuò de", "Old Fednor's", "Old Fednor punya"],
    ["命", "mìng", "life", "nyawa / nyawa"],
    ["。", "", "", ""],
    ["海森", "hǎi sēn", "Haisen", "Haisen"],
    ["立刻", "lì kè", "immediately", "dengan serta-merta"],
    ["给费德诺先生", "gěi fèi dé nuò xiān sheng", "to Mr. Fednor", "menelefon Encik Fednor"],
    ["打来了", "dǎ lái le", "made a (call)", "terus membuat"],
    ["电话", "diàn huà", "telephone call", "panggilan telefon"],
    ["，", "", "", ""],
    ["通报le", "tōng bào le", "notified / reported", "memaklumkan rasmi tentang"],
    ["老费德诺的", "lǎo fèi dé nuò de", "Old Fednor's", "Old Fednor punya"],
    ["病情", "bìng qíng", "state of illness", "keadaan penyakit"],
    ["，", "", "", ""],
    ["恳求他", "kěn qiú tā", "begged him / implored him", "merayu kepada dia agar"],
    ["抽出", "chōu chū", "extract / spare (time)", "meluangkan sedikit"],
    ["一些", "yì xiē", "some", "beberapa / sedikit"],
    ["时间", "shí jiān", "time", "masa"],
    ["到", "dào", "go to", "pergi ke"],
    ["医院", "yī yuàn", "hospital", "hospital"],
    ["去看看", "qù kàn kān", "to visit / see", "untuk melawat melihat"],
    ["老费德诺", "lǎo fèi dé nuò", "Old Fednor", "Old Fednor"],
    ["，", "", "", ""],
    ["这可能是", "zhè kě néng shì", "this probably is", "ini barangkali merupakan"],
    ["他生命的", "tā shēng mìng de", "his life's", "dia punya riwayat nyawa punya"],
    ["最后几天了", "zuì hòu jǐ tiān le", "the very last few days", "beberapa hari yang terakhir sudah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 16 段
    ["费德诺", "fèi dé nuò", "Fednor", "Fednor"],
    ["连连推辞", "lián lián tuī cí", "repeatedly declined / refused", "bertubi-tubi menolak / memberi alasan"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我没有时间", "wǒ méi yǒu shí jiān", "I don't have time", "Saya tidak ada masa"],
    ["，", "", "", ""],
    ["希望你", "xī wàng nǐ", "hope you", "berharap kamu"],
    ["能多陪陪他", "néng duō péi péi tā", "can accompany him more", "dapat lebih menemani beliau"],
    ["，", "", "", ""],
    ["我可以在", "wǒ kě yǐ zài", "I can at", "saya boleh di dalam"],
    ["给你", "gěi nǐ", "give you", "memberi kamu"],
    ["更多的钱", "gèng duō de qián", "more money", "lebih banyak wang lagi"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 17 段
    ["海森", "hǎi sēn", "Haisen", "Haisen"],
    ["生气了", "shēng qì le", "got angry", "menjadi sangat marah"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["费德诺先生", "fèi dé nuò xiān sheng", "Mr. Fednor", "Encik Fednor"],
    ["，", "", "", ""],
    ["在你的眼里", "zài nǐ de yǎn lǐ", "in your eyes", "di dalam matamu"],
    ["只有钱吗", "zhǐ yǒu qián ma", "is there only money", "hanya ada wang sahajakah"],
    ["？", "", "", ""],
    ["他是", "tā shì", "He is", "Beliau adalah"],
    ["你的父亲", "nǐ de fù qīn", "your father", "kamu punya bapa sendiri"],
    ["，", "", "", ""],
    ["他现在", "tā xiàn zài", "he now", "dia sekarang"],
    ["需要你", "nǐ xū yào nǐ", "needs you", "memerlukan kamu"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 18 段
    ["费德诺", "fèi dé nuò", "Fednor", "Fednor"],
    ["也生气了", "yě shēng qì le", "also got angry", "pun turut marah berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["不用你", "bú yòng nǐ", "No need for you", "Tidak payah untuk kamu"],
    ["来教训我", "lái jiào xun wǒ", "to lecture me / teach me a lesson", "datang mengajar / memberi nasihat kepada saya"],
    ["，", "", "", ""],
    ["我知道", "wǒ zhī dào", "I know", "saya tahu"],
    ["该怎么做", "gāi zěn me zuò", "what should be done", "apa yang patut dilakukan"],
    ["！", "", "", ""],
    ["请你", "qǐng nǐ", "Please you", "Sila kamu"],
    ["按照合同做", "àn zhào hé tong zuò", "act according to the contract", "buat mengikut terma kontrak"],
    ["，", "", "", ""],
    ["不然……", "bù rán", "otherwise...", "jika tidak..."],
    ["”", "", "", ""],
    ["他话里的", "tā huà lǐ de", "inside his words'", "dia punya dalam kata-kata punya"],
    ["意思", "yì si", "meaning / implication", "maksud"],
    ["很明白", "hěn míng bai", "very clear", "sangat jelas nyata"],
    ["。", "", "", ""],
    ["海森", "hǎi sēn", "Haisen", "Haisen"],
    ["将面临", "jiāng miàn lín", "will face / confront", "bakal menghadapi"],
    ["巨额", "jù é", "huge sum of / massive", "jumlah yang tersangat besar punya"],
    ["合同赔款", "hé tong péi kuǎn", "contract compensation / penalty", "ganti rugi denda kontrak"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 19 段
    ["海森", "hǎi sēn", "Haisen", "Haisen"],
    ["给气病了", "gěi qì bìng le", "was made sick by anger", "telah jatuh sakit akibat terlalu marah"],
    ["。", "", "", ""],
    ["医生", "yī shēng", "The doctor", "Doktor"],
    ["对他进行了", "duì tā jìn xíng le", "conducted towards him", "telah menjalankan ke atas dia"],
    ["全面的", "quán miàn de", "comprehensive / all-around", "pemeriksaan menyeluruh punya"],
    ["检查", "jiǎn chá", "examination / checkup", "pemeriksaan kesihatan"],
    ["，", "", "", ""],
    ["脸色", "liǎn sè", "complexion / look", "air muka doktor"],
    ["变得", "biàn de", "became", "bertukar menjadi"],
    ["凝重起来", "níng zhòng qǐ lái", "solemn / grave / serious", "sangat serius dan berat"],
    ["。", "", "", ""],
    ["海森", "hǎi sēn", "Haisen", "Haisen"],
    ["开上了", "kāi shàng le", "started making", "mula berseloroh membuat"],
    ["玩笑", "wán xiào", "joke", "gurauan berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你不会是", "nǐ bú huì shì", "You wouldn't be", "Takkanlah doktor nak"],
    ["说在我的", "shuō zài wǒ de", "saying inside my", "cakap di dalam saya punya"],
    ["血液里", "xuè yè lǐ", "inside the blood", "darah"],
    ["化验出了", "huà yàn chū le", "tested out / assayed out", "teruji menemui keluar"],
    ["变异的", "biàn yì de", "mutated's", "variasi mutated punya"],
    ["病毒吧", "bìng dú ba", "virus, right", "virus kan"],
    ["？", "", "", ""],
    ["”", "", "", ""],
    ["医生", "yī shēng", "The doctor", "Doktor itu"],
    ["点了点头", "diǎn le diǎn tóu", "nodded head", "menganggukkan kepala"],
    ["。", "", "", ""],
    ["海森", "hǎi sēn", "Haisen", "Haisen"],
    ["猛地一惊", "měng de yì jīng", "shocked suddenly / startled violently", "terkejut besar dengan tiba-tiba"],
    ["，", "", "", ""],
    ["愤怒地", "fèn nù de", "angrily", "dengan nada penuh kemarahan"],
    ["吼道", "hǒu dào", "roared / bellowed", "menjerit melaung kuat"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["费德诺", "fèi dé nuò", "Fednor", "Fednor"],
    ["，", "", "", ""],
    ["这个混蛋", "zhè ge hún dàn", "this bastard / scoundrel", "si jahanam / bajingan ini"],
    ["，", "", "", ""],
    ["他骗了我", "tā piàn le wǒ", "he cheated me", "dia telah menipu saya"],
    ["！", "", "", ""],
    ["他是", "tā shì", "He is", "Dia adalah"],
    ["制药公司的", "zhì yào gōng sī de", "pharmaceutical company's", "syarikat syarikat farmasi punya"],
    ["老板", "lǎo bǎn", "boss", "bos besar"],
    ["，", "", "", ""],
    ["是", "shì", "is", "adalah"],
    ["赫赫有名的", "hè hè yǒu míng de", "illustrious / celebrated / famous", "pakar yang tersohor gilang-gemilang punya"],
    ["病理学", "bìng lǐ xué", "pathology", "patologi (sains penyakit)"],
    ["专家", "zhuān jiā", "expert / specialist", "pakar pakar"],
    ["，", "", "", ""],
    ["他一定", "tā yí dìng", "he definitely", "dia pasti sudah"],
    ["猜到了", "cāi dào le", "guessed / anticipated", "meneka mendapati bahawa"],
    ["老费德诺", "lǎo fèi dé nuò", "Old Fednor's", "Old Fednor punya"],
    ["身体里的", "shēn tǐ lǐ de", "inside the body's", "dalam badan punya"],
    ["病毒", "bìng dú", "virus", "virus"],
    ["有传染性", "yǒu chuán rǎn xìng", "has infectivity / contagious", "mempunyai sifat berjangkit"],
    ["。", "", "", ""],
    ["这个混蛋", "zhè ge hún dàn", "this bastard", "Si jahanam ini"],
    ["，", "", "", ""],
    ["他让我", "tā ràng wǒ", "he let me", "dia biarkan saya"],
    ["替他", "tì tā", "replace him to / on his behalf", "bagi pihak dia / menggantikan dia"],
    ["得了病", "dé bìng le", "got sick", "mendapat penyakit ini"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 20 段
    ["第二天", "dì èr tīan", "The next day", "Keesokan harinya"],
    ["下午", "xià wǔ", "afternoon", "petang"],
    ["，", "", "", ""],
    ["又到了", "yòu dào le", "again arrived at", "sekali lagi sampai ke masa"],
    ["他该去", "tā gāi qù", "he should go to", "dia sepatutnya pergi"],
    ["陪伴", "péi bàn", "accompany", "menemani"],
    ["老费德诺的", "lǎo fèi dé nuò de", "Old Fednor's", "Old Fednor punya"],
    ["时间", "shí jiān", "time", "waktu"],
    ["。", "", "", ""],
    ["他本来", "tā běn lái", "He originally", "Dia pada asalnya"],
    ["已经", "yǐ jīng", "already", "sudah pun"],
    ["恨透了", "hèn tòu le", "hated thoroughly", "benci tersangat pekat kepada"],
    ["费德诺", "fèi dé nuò", "Fednor", "Fednor"],
    ["，", "", "", ""],
    ["下定决心", "xià dìng jué xīn", "made up mind", "mengambil tekad azam"],
    ["不再", "bú zài", "no longer", "tidak akan lagi"],
    ["替他", "tì tā", "on his behalf", "bagi pihak dia"],
    ["装下去了", "zhuāng xià qù le", "continue pretending", "berpura-pura berlakon lagi"],
    ["，", "", "", ""],
    ["但时间一到", "dàn shí jiān yí dào", "but as soon as time arrived", "namun sebaik sahaja waktu sampai"],
    ["，", "", "", ""],
    ["他就", "tā jiù", "he then", "dia terus"],
    ["再也坐不住了", "zài yě zuò bú zhù le", "could not sit still anymore", "langsung tidak boleh duduk diam lagi"],
    ["，", "", "", ""],
    ["还是", "hái shì", "still", "tetap juga"],
    ["悄悄溜出", "qiāo qiāo liū chū", "quietly slipped out of", "menyelinap keluar secara senyap dari"],
    ["医院", "yī yuàn", "hospital", "hospital"],
    ["，", "", "", ""],
    ["换上了", "huàn shàng le", "put on (clothes/gear)", "menukar memakai"],
    ["行头", "xíng tou", "actor's outfit / costume", "pakaian lakonannya"],
    ["，", "", "", ""],
    ["戴上了", "dài shàng le", "put on (mask)", "memakai"],
    ["面具", "miàn jù", "mask", "topeng wajah"],
    ["，", "", "", ""],
    ["赶到了", "gǎn dào le", "rushed to", "bergegas sampai ke"],
    ["老费德诺的", "lǎo fèi dé nuò de", "Old Fednor's", "Old Fednor punya"],
    ["病房", "bìng fáng", "ward", "bilik wad pesakit"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 21 段
    ["老费德诺", "lǎo fèi dé nuò", "Old Fednor", "Old Fednor"],
    ["躺在", "tǎng zài", "lying on", "terbaring di atas"],
    ["病床上", "bìng chuáng shàng", "sickbed", "katil wad pesakit"],
    ["，", "", "", ""],
    ["有气无力地", "yǒu qì wú lì de", "feebly / weakly", "dengan nada yang tersangat lemah tanpa tenaga"],
    ["对他说", "duì tā shuō", "said to him", "berkata kepada dia"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我以为", "wǒ cāi yǐ wéi", "I assumed", "Bapa menyangka"],
    ["你不会来了", "nǐ bú huì lái le", "you wouldn't come anymore", "kamu tidak akan datang lagi sudah"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["海森", "hǎi sēn", "Haisen", "Haisen"],
    ["笑了", "xiào le", "smiled / laughed", "tersenyum lalu berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["为什么不来", "wèi shén me bù lái", "Why not come", "Mengapa tidak datang pula"],
    ["？", "", "", ""],
    ["我听到了", "wǒ tīng dào le", "I heard", "Saya ada terdengar"],
    ["好几个", "hǎo jǐ gè", "several", "beberapa buah"],
    ["笑话", "xiào hua", "jokes", "cerita jenaka"],
    ["，", "", "", ""],
    ["一定要", "yí dìng yào", "definitely must", "mesti wajib"],
    ["讲给你呢", "jiǎng gěi nǐ ne", "tell to you", "ceritakan kepada bapa ni"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 22 段
    ["老费德诺", "lǎo fèi dé nuò", "Old Fednor", "Old Fednor"],
    ["欣慰地", "xīn wèi de", "gratifiedly / with relief", "dengan penuh rasa lega dan gembira"],
    ["望着他", "wàng zhe tā", "gazing at him", "memandang wajahnya"],
    ["，", "", "", ""],
    ["点了点头", "diǎn le diǎn tóu", "nodded head", "menganggukkan kepala"],
    ["，", "", "", ""],
    ["眼睛里", "yǎn jing lǐ", "inside the eyes", "dalam mata beliau"],
    ["竟闪烁着", "jìng shǎn shuò zhe", "unexpectedly twinkled with", "malah kelihatan berkaca bersinar dengan"],
    ["泪光", "lèi guāng", "tears", "air mata kesayuan"],
    ["。", "", "", ""],
    ["他一挥手", "tā yì huī shǒu", "He as soon as waving hand", "Sebaik sahaja beliau melambaikan tangan"],
    ["，", "", "", ""],
    ["从门外", "cóng mén wài", "from outside the door", "dari luar pintu"],
    ["进来", "jìn lái", "entered inside", "melangkah masuk ke dalam"],
    ["两个", "liǎng gè", "two", "dua orang"],
    ["年轻人", "nián qīng rén", "young men", "pemuda"],
    ["，", "", "", ""],
    ["他们是", "tā men shì", "they were", "mereka adalah"],
    ["老费德诺的", "lǎo fèi dé nuò de", "Old Fednor's", "Old Fednor punya"],
    ["律师", "lǜ shī", "lawyers", "peguam perundangan"],
    ["。", "", "", ""],
    ["老费德诺", "lǎo fèi dé nuò", "Old Fednor", "Old Fednor"],
    ["对海森", "duì hǎi sēn", "to Haisen", "kepada Haisen"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["先生", "xiān sheng", "Sir / Gentleman", "Tuan"],
    ["，", "", "", ""],
    ["请告诉我", "qǐng gào su wǒ", "please tell me", "sila beritahu kepada bapa"],
    ["你的名字", "nǐ de míng zi", "your name", "kamu punya nama yang sebenar"],
    ["。", "", "", ""],
    ["我已经", "wǒ yǐ jīng", "I have already", "Bapa sudah pun"],
    ["立下了", "lì xià le", "set down / established", "membuat rasmi"],
    ["遗嘱", "yí zhǔ", "will / testament", "surat wasiat harta"],
    ["，", "", "", ""],
    ["要把财产", "yào bǎ cái chǎn", "want to asset / property", "mahu menyerahkan harta benda"],
    ["全部", "quán bù", "completely / all", "sepenuhnya semua sekali"],
    ["转给你", "zhuǎn gěi nǐ", "transfer to you", "dipindahkan hak milik kepada kamu"],
    ["了", "le", "out", ""],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["海森一愣", "hǎi sēn yí lèng", "Haisen was stunned", "Haisen terus tergamam terpegun"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你早就", "nǐ zǎo jiù", "you already long ago", "Bapa sudah lama sangat"],
    ["看出了", "kàn chū le", "discovered / saw out", "nampak mendapati bahawa"],
    ["我不是", "wǒ bú shì", "I am not", "saya bukan"],
    ["你的儿子", "nǐ de fù qīn", "your son", "bapa punya anak kandung"],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 23 段
    ["老费德诺", "lǎo fèi dé nuò", "Old Fednor", "Old Fednor"],
    ["点了点头", "diǎn le diǎn tóu", "nodded head", "menganggukkan kepala"],
    ["，", "", "", ""],
    ["目光中", "mù guāng zhōng", "inside the gaze / eyes expression", "dalam pandangan mata beliau"],
    ["满是", "mǎn shì", "full of", "sarat dipenuhi dengan rasa"],
    ["辛酸", "xīn suān", "sadness / bitterness / pungent", "kesedihan pilu / kepasrahan hampa"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["儿子的一言一行", "ér zi de yì yán yì xíng", "son's every word and action", "Anak kandung punya setiap kata-kata dan cara kerja"],
    ["、", "", "", ""],
    ["一颦一笑", "yì pín yí xiào", "every frown and smile", "setiap senyuman dan jelingan air muka"],
    ["，", "", "", ""],
    ["都装在", "dōu zhuāng zài", "all packed inside", "semuanya tersimpan rapat di dalam"],
    ["我的脑子里", "wǒ de nǎo zi lǐ", "inside my brain", "bapa punya akal fikiran kepala"],
    ["了", "le", "out", ""],
    ["。", "", "", ""],
    ["自打你", "zì dǎ nǐ", "Ever since you", "Semenjak daripada hari pertama kamu"],
    ["一进门", "yī jìn mén", "as soon as entering the door", "melangkah masuk ke dalam pintu"],
    ["，", "", "", ""],
    ["我就", "wǒ jiù", "I straightaway", "bapa terus"],
    ["看出你", "kàn chū nǐ", "saw out you", "nampak kamu"],
    ["是假冒的了", "shì jiǎ mào de le", "was fake / counterfeit", "adalah menyamar palsu sahaja"],
    ["。", "", "", ""],
    ["但我很", "dàn wǒ hěn", "But I very", "Namun bapa sangat"],
    ["喜欢你", "xǐ huan nǐ", "like you", "menyayangi kamu"],
    ["，", "", "", ""],
    ["孩子", "hái zi", "child", "anakku"],
    ["。", "", "", ""],
    ["你给我", "nǐ gěi wǒ", "You for me", "Kamu kepada bapa"],
    ["带来了", "dài lái le", "brought over", "telah membawa bersama"],
    ["快乐", "kuài lè", "happiness", "kegembiraan riang"],
    ["，", "", "", ""],
    ["我的生活", "wǒ de shēng huó", "my life", "bapa punya baki hidup"],
    ["变得", "biàn de", "became", "bertukar menjadi"],
    ["有滋有味", "yǒu zī yǒu wèi", "meaningful / full of flavor", "penuh berseri bermakna"],
    ["，", "", "", ""],
    ["我每天", "wǒ měi tīan", "I every day", "bapa setiap hari"],
    ["都在盼着", "dōu zài pàn zhe", "all are looking forward to", "asyik tertunggu-tunggu"],
    ["你来呢", "nǐ lái ne", "your coming", "kamu datang ni"],
    ["，", "", "", ""],
    ["就连那个", "jiù lián nà gè", "even that", "bahkan virus yang"],
    ["可怕的", "kě pà de", "frightening", "menakutkan itu"],
    ["病毒", "bìng dú", "virus", "pun"],
    ["，", "", "", ""],
    ["也被你的", "yě bèi nǐ de", "also by your", "turut oleh kamu punya"],
    ["快乐", "kuài lè", "happiness", "kegembiraan riang"],
    ["赶跑了", "gǎn pǎo le", "chased away", "berjaya dihalau pergi jauh"],
    ["了", "le", "out", ""],
    ["。", "", "", ""],
    ["我真要", "wǒ zhēn yào", "I truly want to", "Bapa sungguh mahu"],
    ["谢谢你啊", "xiè xie nǐ ā", "thank you", "mengucapkan terima kasih kepada kamu"],
    ["，", "", "", ""],
    ["孩子", "hái zi", "child", "anakku"],
    ["处理", "", "", ""],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["海森", "hǎi sēn", "Haisen", "Haisen"],
    ["更是惊愕了", "gèng shì jīng è le", "was even more astounded / stunned", "menjadi teramat gempar terkejut besar lagi"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你都好了", "nǐ dōu hǎo le", "You are all recovered", "Bapa dah sembuh sepenuhnya"],
    ["？", "", "", ""],
    ["那", "nà", "Then", "Maka"],
    ["，", "", "", ""],
    ["那个病毒……", "nà gè bìng dú", "that virus...", "virus bengkak yang tenat itu..."],
    ["”", "", "", ""],
    ["老费德诺", "lǎo fèi dé nuò", "Old Fednor", "Old Fednor"],
    ["得意地", "dé yì de", "proudly / complacently", "dengan nada ceria tersenyum menang"],
    ["笑了", "xiào le", "smiled", "tertawa sedikit"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["那是", "nà shì", "That was", "Itu semestinya adalah"],
    ["我和医生", "wǒ hé yī shēng", "me and doctor", "bapa dengan pihak doktor"],
    ["合演的", "hé yǎn de", "co-acted / performed together", "saling bersepakat berlakon punya"],
    ["一出戏", "yì chū xì", "a drama / a play", "satu sandiwara sahaja"],
    ["，", "", "", ""],
    ["我的孩子", "wǒ de hái zi", "my child", "anakku"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["海森", "hǎi sēn", "Haisen", "Haisen"],
    ["心下一松", "xīn xià yì sōng", "mind relaxed / heart eased", "hati menjadi sangat lega lapang"],
    ["，", "", "", ""],
    ["伸手", "shēn shǒu", "stretched out hand", "menghulurkan tangan"],
    ["准备", "zhǔn bèi", "prepared", "bersedia"],
    ["去揭下", "qù jiē xià", "to peel off / remove", "untuk menanggalkan keluar"],
    ["脸上的", "liǎn shàng de", "on the face's", "pada muka punya"],
    ["面具", "miàn jù", "mask", "topeng wajah"],
    ["。", "", "", ""],
    ["老费德诺", "lǎo fèi dé nuò", "Old Fednor", "Old Fednor"],
    ["阻拦了", "zǔ lán le", "stopped / blocked", "menghalang menyekat"],
    ["他", "tā", "him", "dia"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["别揭掉它", "bié jiē diào tā", "Don't peel it off", "Jangan tanggalkannya keluar"],
    ["，", "", "", ""],
    ["孩子", "hái zi", "child", "anakku"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["海森", "hǎi sēn", "Haisen", "Haisen"],
    ["愣住了", "lèng zhù le", "stunned", "terpaku hairan"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你都", "nǐ dōu", "you already all", "Bapa pun dah"],
    ["知道了", "zhī dào le", "knew", "tahu sepenuhnya bahawa"],
    ["我是", "wǒ shì", "I am", "saya adalah"],
    ["假冒的了", "shì jiǎ mào de le", "fake", "menyamar palsu"],
    ["，", "", "", ""],
    ["我还戴着它", "wǒ hái dài zhe tā", "I still wearing it", "apa sebab saya masih pakai ia"],
    ["干什么呢", "gàn shén me ne", "doing what for", "lagi ya"],
    ["？", "", "", ""],
    ["”", "", "", ""],
    ["老费德诺", "lǎo fèi dé nuò", "Old Fednor", "Old Fednor"],
    ["痛苦地", "tòng kǔ de", "painfully", "dengan penuh perit luluh sedih"],
    ["摇了摇头", "yáo le yáo tóu", "shook head", "menggeleng-gelengkan kepala"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你这就", "nǐ jiù", "You just", "Kamu tolonglah tetap"],
    ["给我留下", "gěi wǒ liú xià", "leave behind for me", "tinggalkan kepada bapa baki"],
    ["这最后的一点儿", "zhè zuì hòu de yì diǎnr", "this very last little bit of", "secuil yang terakhir ini punya"],
    ["希冀吧", "xī jì ba", "hope / yearning", "harapan tipis sisa / impian"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["海森", "hǎi sēn", "Haisen", "Haisen"],
    ["点了点头", "diǎn le diǎn tóu", "nodded head", "menganggukkan kepala"],
    ["，", "", "", ""],
    ["勉强地", "miǎn qiǎng de", "reluctantly / with an effort", "dengan sangat terpaksa senget"],
    ["挤出了", "jǐ chū le", "squeezed out", "mengukir keluar"],
    ["一丝笑容", "yì sī xiào róng", "a hint of smile", "secuil senyuman kelat"],
    ["，", "", "", ""],
    ["重新", "chóng xīn", "anew / again", "sekali lagi semula"],
    ["把那个", "bǎ nà gè", "object particle that", "membawa topeng wajah yang itu"],
    ["费德诺的", "fèi dé nuò de", "Fednor's", "Fednor punya"],
    ["面具", "miàn jù", "mask", "topeng wajah"],
    ["戴好", "dài hǎo", "put on well", "dipakai dengan kemas"],
    ["了", "le", "out", ""],
    ["。", "", "", ""]
];
